uploads = []
generated = []

[[outputs]]
id = "tcyolDtp59h7Uy4fuMGJD"
uri = "file://jazzmax_20260522_1959.zip"
type = "unspecified"
title = "JazzMAX Project Export — jazzmax_20260522_1959.zip"

[[outputs]]
id = "Aoy7IM1r_fFFew_9-IYGb"
uri = "file://jazzmax_20260522_2004.zip"
type = "unspecified"
title = "JazzMAX Project Export — 2.5 MB"
